### ISSUE TITLE
Compiler should indicate line:column when reporting a type mismatch

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#104]
Currently compiler will only report like this

```
error: type mismatch:
  expected: ‘PolyList PolyList A’
    actual: ‘PolyList A’
```

I won't be able to know where the type mismatch happens exactly, unless I compile the file every time I modify one single component, or remove those new lines one by one to find out which line to blame.

That wastes time!!

**Comment by zonyitoo** [comment]
May relate to #90

**Comment by zhiyuanshi** [comment]
Duplicate issue
