### ISSUE TITLE
Support variable names starting with underscore

### ISSUE THREAD

**Issue by wxzh** [hkuplg/fcore#107]
`_x1` is a valid variable name while `_1x` and `_` are not valid.

**Comment by zonyitoo** [comment]
Why `_1x` is not valid?

**Comment by wxzh** [comment]
In principle, even `_1` should be valid. But to avoid potential interference with tuple projection (see #103 discussion). We force users to write this way for now. It can be improved later.

**Comment by zonyitoo** [comment]
@wxzh Indeed. It would be fixed when pattern matching on Tuples is ready.

**Comment by bixuanzju** [comment]
@zonyitoo Tuple in f2j is a primitive type, not a datatype like in Haskell. So pattern matching on tuples needs some major changes in backend. Let's close this issue.

**Comment by zonyitoo** [comment]
@bixuanzju Alright, never mind.
