### ISSUE TITLE
The type parameter of functions that have only one generic typed parameter should not be omited

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#111]
```
let func[A] (x : A) = x;
func 1
```

This works in F2J currently. Then why shouldn't this work

```
data Maybe[A] = Just A
              | Nothing;
Just 1
```

or neither of them should work

**Comment by bixuanzju** [comment]
The first example looks like we have type inference working for it. I guess type inference is still work in process.

**Comment by zonyitoo** [comment]
@bixuanzju : @zhiyuanshi told me that is just a special case

**Comment by bixuanzju** [comment]
@zonyitoo This issue is about type inference, which is yet to be implemented. For now, you can think we need types everywhere.

If you are OK, I'd like to close it.

**Comment by zonyitoo** [comment]
@bixuanzju Nope. I am not asking for type inference in this issue. I just asking why the first example is a special case?

**Comment by bixuanzju** [comment]
@zonyitoo I asked George about that. This is because it is very easy to implement in the first example, he did it just for convenience. If you dislike, we can comment out affected code. In general, you need to write type arguments everywhere.

**Comment by zonyitoo** [comment]
@bixuanzju Alright. Understood.
