### ISSUE TITLE
Require support of unary operator

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#116]
Unary operator, such as `!`, `~`, `-`, ... should be supported, because I cannot do this currently

```
let fn : Bool = True;

!(fn)  -- It seems that there is no other way to get the "not" value of `fn`
```

**Comment by zonyitoo** [comment]
@bixuanzju Is it easy to implement?

**Comment by bixuanzju** [comment]
@zonyitoo I suppose, but do ask George for help.

**Comment by bixuanzju** [comment]
@zonyitoo I ask @lihuanglx to implement it. For the moment, could you just define your own version of `not`, say

```
not (x : Bool) = if x == True then False else True
```

**Comment by zonyitoo** [comment]
@bixuanzju Alright, thanks.

**Comment by bixuanzju** [comment]
@lihuanglx Hi, what is the status now?

**Comment by lihuanglx** [comment]
Working on it.

**Comment by bixuanzju** [comment]
@zonyitoo adding unary operators could possibly cause parsing ambiguities. We decide to only support unary minus `-`, but you have to explicitly add brackets when you mean so, e.g., `f -3` will be parsed as binary subtraction `f - 3`, while `f (-3)` is parsed to `f` applied to `-3`, just like Haskell. For boolean `not`, it'e better to treat it as a function, before we have some sort of `Prelude` library, you have to define it yourself.

**Comment by lihuanglx** [comment]
Or use `== False` instead of `not`.

**Comment by zonyitoo** [comment]
@bixuanzju understood.
