### ISSUE TITLE
Conflict definition of classes

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#117]
Currently `thunk.sf` will be compiled to Java as a class named `Thunk`, so if I defined a

```
data Thunk = ...
```

in `thunk.sf`, then javac will report duplicated definition of `Thunk`.

**Comment by bixuanzju** [comment]
Right! In runtime, we also have a Java file named `Thunk`. You'd better not use that name.

**Comment by zonyitoo** [comment]
@bixuanzju `Thunk` is just an example. No matter what I name this, it should not be duplicated.

**Comment by bixuanzju** [comment]
Sorry I misunderstood you question.

**Comment by xnning** [comment]
having a file named `fun1.sf`
with code

```
let a (x:Int) = x;
2
```

will generate

```
fun1 using [Naive]
Compiling to Java source code ( examples\Fun1.java )
examples\Fun1.java:5: 错误: 已在程序包 未命名程序包中定义了类 Fun1
    class Fun1 extends f2j.Closure
    ^
1 个错误
```

file name will clash with any generated class name in runtime.

**Comment by xnning** [comment]
sorry the error message is in Chinese...

it says duplicated class definitions of Fun1

**Comment by zonyitoo** [comment]
Thanks @xnning for clarifying the question...

**Comment by bixuanzju** [comment]
@zonyitoo Those `Fun*` class definitions are generated by the compiler. It's hard-coded in it. Let me see if I can change the file name if conflicts.

@xnning I am not familiar with `datatype` generation. Seems the generated class will reuse the same name as in the program. Do you have any way to workaround it?

**Comment by zonyitoo** [comment]
@bixuanzju I think if the #34 solved, then this problem won't be existed.

**Comment by wxzh** [comment]
For now, every generated datatype class in java has the name of the corresponding datatype declaration in user programs. This naming strategy which will cause error if the file shares any one of datatype names.

A potential workaround can be: using "filename + datatype name" to be the name of datatype classes instead of using the user-provided names directly.

**Comment by zonyitoo** [comment]
@wxzh or we should come up with a name mangling style.

**Comment by xnning** [comment]
`Fun*` `Let*` and datatype, these three things may use a common strategy to void the name clash?

@zonyitoo i think issue 34 is not related to this one. Anyway, file name can be anything.

@wxzh  this seems feasible.

**Comment by bixuanzju** [comment]
@xnning Do you want to tackle it?

**Comment by xnning** [comment]
@bixuanzju ok, it's mine! Use the strategy weixin suggest?

**Comment by bixuanzju** [comment]
@EmmaBYPeng Emma, could look at commit c441f92, I added a test case named "Fun1.sf", `make test2` read

> Incorrect: java.lang.ClassNotFoundException: Fun1: null

I can run the file manually.

**Comment by EmmaBYPeng** [comment]
What about `make test`?

**Comment by bixuanzju** [comment]
Don't use `make test` now. It's fake (won't report anything useful)

**Comment by EmmaBYPeng** [comment]
Ok, let me see what I can do!

**Comment by EmmaBYPeng** [comment]
@bixuanzju Hi jeremy I tried `f2j -r Fun1.sf` and got `./Fun1.java:5: error: class Fun1 is already defined in package unnamed package
    class Fun1 extends f2j.Closure
    ^
1 error
Error: Could not find or load main class Fun1`

**Comment by bixuanzju** [comment]
@EmmaBYPeng You didn't pull the latest code?

**Comment by EmmaBYPeng** [comment]
Yes I did.

**Comment by bixuanzju** [comment]
That's odd...

![screen shot 2015-03-15 at 4 21 34 pm](https://cloud.githubusercontent.com/assets/1680704/6655213/610c5fca-cb2f-11e4-8f0b-69857fe5e9b3.png)

**Comment by EmmaBYPeng** [comment]
Ah I forgot to make...

**Comment by EmmaBYPeng** [comment]
@bixuanzju `make test2` uses `sf2java False NoDump opt className contents` to translate systemF to java, would it be a problem?

**Comment by bixuanzju** [comment]
For datatype name clash, see #119

**Comment by xnning** [comment]
Is it a temporary hack? will compiler use front end name in generated file in the future, such as #34?

**Comment by bixuanzju** [comment]
@xnning Sort of. Even if #34 is resolved, there are still chances that function name will conflict with the file name.

**Comment by xnning** [comment]
@bixuanzju Currently each class name ends with numbers (except data type), so changing the file name can work. It is not the case when #34 is resolved?

**Comment by bixuanzju** [comment]
For example, if I name the file `foo.hs`, inside it a function definition, say

```
let foo = \ (x : Int) -> x + 1
```

Then the function name `foo` will be propagated to the generated Java file, so there will be a Java class named `Foo`, and it conflicts with the file name, which is `Foo.java`.

**Comment by tomtau** [comment]
I think we can use Scala's approach: http://www.scala-lang.org/old/node/12186.html

'$' can be used in Java identifiers, but noone knows about it or uses it (no problem to disallow it in the source language identifiers), so it's a good character for name mangling in generated names.

**Comment by xnning** [comment]
@bixuanzju yes exactly. So after #34 is finished, function name can be anything, just like data type name can be anything. So these two may use the same strategy to avoid name clash. File name changing can not handle it.
