### ISSUE TITLE
closuref fail in data type

### ISSUE THREAD

**Issue by xnning** [hkuplg/fcore#119]
dumpclosuref fails.

```
fcore> f2j examples\datatype\is_nil.sf --dump=dumpclosuref
is_nil using [Naive]
Compiling to Java source code ( examples\datatype\Is_nil.java )
data PolyList A = Nil
f2j: panic! (the 'impossible' happened)
transType: TVar "A"
```

besides, duplicated cases should not be allowed when type check

```
case e of
    Nil -> False
  | Nil -> True
```

**Comment by wxzh** [comment]
Duplicated patterns should be allowed if we want to do deep pattern matching in the future, e.g.,

```
case e of
    Cons x Nil -> ...
  | Cons x xs -> ...
```

For now, we must make sure that latter duplicated patterns will be never executed.

**Comment by xnning** [comment]
@wxzh  Agree.

**Comment by bixuanzju** [comment]
@xnning Hi Ningning, what's the status of this issue?

**Comment by xnning** [comment]
@bixuanzju this is finished. duplicated cases may be enhanced in the future.
the data type part in #117 is not yet. Btw, the changing file name strategy is a temporary solution?

**Comment by bixuanzju** [comment]
@xnning Yes!

**Comment by bixuanzju** [comment]
@xnning I tried the data type example in #117 , now it's ok. Why do you consider it's not yet finished?

**Comment by xnning** [comment]
a file name`apple`
with code

```
data Apples = ...
```

**Comment by bixuanzju** [comment]
@xnning Alright, let's keep the issue open.

**Comment by xnning** [comment]
@bixuanzju  how about making it separated from the name clash problem.

**Comment by bixuanzju** [comment]
@xnning As Tomas suggested, what about adding `$` suffix to the datatype class name?
