### ISSUE TITLE
Cannot import/construct normal Java object

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#121]
```
new java.lang.StringBuffer()
                          ^~~~ Parse Error
```

```
new java.util.HashMap<Int, Int>()
                     ^~~~ Parse Error. Does not support generic in Java style.
```

And there is no way to import Java packages.

**Comment by bixuanzju** [comment]
In the first example, to workaround, try

```
new java.lang.StringBuffer( )
```

This is a known issue #97 

We won't support generic Java interoperation natively. One way to achieve the similar effect is to wrap it into non-generic method call in your own Java file, and let `f2j` compiler know it.

**Comment by zonyitoo** [comment]
@bixuanzju the workaround seems magic hack... could it be fixed?

**Comment by lihuanglx** [comment]
@zonyitoo That's because we also have unit as `()`, the parser will get confused.

I suggest you to use this hack for now, when it get fixed you could simply replace all `( )` with `()` in your code.

**Comment by zonyitoo** [comment]
@lihuanglx ah, i see. thanks.
