### ISSUE TITLE
Document how Windows users can compile the project

### ISSUE THREAD

**Issue by bixuanzju** [hkuplg/fcore#124]

**Comment by linusyang** [comment]
MinGHC could be a handy GHC compiler platform for Windows users. No need to install the large Haskell platform.
https://github.com/fpco/minghc
https://www.fpcomplete.com/blog/2015/03/minghc-ghc-7-10

**Comment by bixuanzju** [comment]
Installing Haskell platform isn't hard, the problem is some libraries can't be installed on Windows easily. I remember last time I tried, I couldn't get `network` package right

**Comment by linusyang** [comment]
@bixuanzju That's exactly why I recommend [this one](https://www.fpcomplete.com/blog/2015/03/minghc-ghc-7-10):

> MSYS, which is necessary for building some packages such as network

**Comment by bixuanzju** [comment]
@linusyang trying now, haha

**Comment by bixuanzju** [comment]
The [stack](https://github.com/commercialhaskell/stack) tool solves problem of installing on Windows. When we switch to using stack, this could be closed.
