### ISSUE TITLE
Failed to handle Java Array

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#125]
``` java
java.lang.Character.toChars(20)
```

This function should return a `char[]`, but compiler failed to handle it.

What I want to do is to convert a Unicode codepoint to a String.

``` java
new java.lang.String(java.lang.Character.toChars(codepoint))
```

**Comment by bixuanzju** [comment]
This is one restriction of our Java interoperation. Seems we only support class types. I am not sure `char[]` in Java is a primitive type or a class type.

**Comment by bixuanzju** [comment]
@zonyitoo I find out what goes wrong. Need to investigate a bit.

**Comment by bixuanzju** [comment]
@zonyitoo It this fixed for you?

**Comment by zonyitoo** [comment]
Please try the following code snippet

```
new java.lang.String(java.lang.Character.toChars(20))
```

Compiler should report

```
error: NoSuchConstructor "java.lang.String" ["char[]"]
```

**Comment by bixuanzju** [comment]
Noted that. Seems type server doesn't know `char[]` and `String` can be used interchangeably.

**Comment by bixuanzju** [comment]
@zonyitoo Does that fix for you?

**Comment by zonyitoo** [comment]
@bixuanzju Yes, it fixed.
