### ISSUE TITLE
Add feature for embedding Java code

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#126]
Just for brainstorming ;)

```
@JavaType
type HashMap[K, V] = java.util.HashMap<K, V>;

@JavaCode
let new[K, V] : HashMap[K, V] = {
    return new java.util.HashMap<K, V>();
};

@JavaCode
let insert[K, V] (map: HashMap[K, V]) (k : K) (v : V) : Unit = {
    map.insert(k, v);
};
```

This feature also enables the possibility to support generic Java types.

**Comment by bixuanzju** [comment]
Won't support.  We have options:
1. support cast in f2j (promising?)
2. support restricted java generics (unbound type parameters)

**Comment by zonyitoo** [comment]
@bixuanzju I think it should be a choice to support Java code via syntax like FFI.

**Comment by bixuanzju** [comment]
@zonyitoo It's more complicated than it looks. Basically we need to understand whole Java type system, which is not our goal in the first place. However, as we discussed in today's seminar with Bruno, we can support casting natively, which allows you to cast  generic type to a specific type. But that needs further investigation.
