### ISSUE TITLE
Should map `==` to `.equals` method call

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#127]
```
let intEqual (a : Int) (b : Int) : Bool = (a == b);

intEqual 160 160
```

This program displays `false` because it actually use `==` in Java, which is not going to test the equality of this two objects but just test whether they are the same object.

**Comment by bixuanzju** [comment]
In the future, when unboxing is finished, `Int` in `intEqual` would be mapped to Java primitive `int`, and we can only use `==` to compare.

@tomtau What do you think?

**Comment by tomtau** [comment]
it'll be mapped to long, but the rest of the story is the same for primitive types

**Comment by bixuanzju** [comment]
@zonyitoo For now, I think you have to explicitly call `.equlas` on the object. We will leave this open for future work.

**Comment by tomtau** [comment]
will disappear with https://github.com/hkuplg/fcore/issues/30
