### ISSUE TITLE
"Supernaive" compilation option

### ISSUE THREAD

**Issue by tomtau** [hkuplg/fcore#128]
Currently, even the naive option still performs source-level optimizations with partial evaluation... mainly for development purposes (as a sanity check), it would be good to generate and test completely unoptimized code.

**Comment by bixuanzju** [comment]
I don't understand. Could you give a simple example of completely unoptimized code?

**Comment by tomtau** [comment]
((x : Int) -> x) (1+1)

peval would optimize away the id lambda and translate it as:
(1+1)

**Comment by bixuanzju** [comment]
I see, that's mainly for reversing the effects of simplify (my seminar topic last week :)... I can disable that in the "Supernaive" option.

**Comment by bixuanzju** [comment]
@tomtau There's one thing, If I remove `peval` part, then the generated code will have superfluous identity functions (because of `simplify` you know). So 

```
((x : Int) -> x) (1+1)
```

would actually become 

```
((x : Int) -> x) (\(x : Int) -> x) (1+1))
```

Do you consider that completely unoptimized code?

**Comment by tomtau** [comment]
It would be ideal if it could still be:
((x : Int) -> x) (1+1)

But with extra identity functions, it's fine - i.e. it should still work.
