### ISSUE TITLE
Add prelude libraries

### ISSUE THREAD

**Issue by bixuanzju** [hkuplg/fcore#131]
Add libraries for `List`, and other convenient datatypes and related functions.

**Comment by zonyitoo** [comment]
List should have at least three types: PolyList, LazyPolyList, ArrayList. ;)

**Comment by bixuanzju** [comment]
@zhiyuanshi Can it be closed?

**Comment by zonyitoo** [comment]
@bixuanzju We have module system now?

**Comment by bixuanzju** [comment]
@zonyitoo no, but we have some sort of predefined library

**Comment by zonyitoo** [comment]
which is defined as a token?

**Comment by bixuanzju** [comment]
@zonyitoo have a look at lib/predef/

**Comment by zonyitoo** [comment]
@bixuanzju How did they work? How to include that in my code?

**Comment by bixuanzju** [comment]
As the name suggests, it's a prelude library as in Haskell, so you can't possibly extend it in client code I guess. Better ask @zhiyuanshi

**Comment by zhiyuanshi** [comment]
@zonyitoo You don't need to do anything. The definitions there, which are part of the compiler, are already in scope for programs you write. The current implementation is just pasting Predef before your code.

**Comment by zonyitoo** [comment]
@zhiyuanshi Oh, well, that means the prelude library cannot have dependencies between each others.

**Comment by zhiyuanshi** [comment]
They can, as Predef can consist of multiple files. But of course, circular dependency is not allowed.

**Comment by zonyitoo** [comment]
Consider I have preluded files named `list.sf` and `listops.sf`, those functions in `listops.sf` are depend on the list definitions in `list.sf`. But now you don't have things to tell the compiler that `listops.sf` is depending on `list.sf`, so if you paste `listops.sf` before `list.sf`, that won't compile.

Or you have a better idea to solve this dependencies problem without explicit declaration in the source code?

**Comment by zhiyuanshi** [comment]
@zonyitoo Right now I think the order of sticking them together is hardcoded in the compiler. So unless you change the source code in Haskell, you have no control of the actual order.

**Comment by bixuanzju** [comment]
A basic module system that supports separate compilation is almost done. Once we finish declaring datatypes inside a module, adding prelude should be simple.

**Comment by bixuanzju** [comment]
prelude is added. declaring datatypes in a module is another issue #201
