### ISSUE TITLE
Build failed with the latest commit

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#132]
```
type StringBuilder = java.lang.StringBuilder;
```

Compiler reports a parse error.

**Comment by zonyitoo** [comment]
Looks like compiler will "desuger"  `java.lang.StringBuilder` to `java.lang_StringBuilder`.

@EmmaBYPeng It is broken...

@bixuanzju Looks like the `.` will produce ambiguous in F2J.

**Comment by EmmaBYPeng** [comment]
Should be working now.

**Comment by bixuanzju** [comment]
@EmmaBYPeng Good! I'd like to ask how to run `dataM.sf` file in example directory?

**Comment by EmmaBYPeng** [comment]
@bixuanzju Simply `f2j -r dataM.sf` should work~

**Comment by EmmaBYPeng** [comment]
@bixuanzju Umm but it needs commit [a411e63](https://github.com/hkuplg/fcore/commit/a411e6ce09f66a33aee03a8e4b7af1e51cb33caf) to work

**Comment by bixuanzju** [comment]
@EmmaBYPeng  I see, I will revert that change
