### ISSUE TITLE
Add support of block comment

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#133]
```
{-
  commenting
  xxx  {-  nested? -}
-}
```

It should be easy to do.

**Comment by bixuanzju** [comment]
@linusyang Hi Linus, do you want to tackle this?

**Comment by linusyang** [comment]
@bixuanzju Of course. I think this is also related to the implementation of string interpolation. I may find a solution to both of functions by using _start codes_ of alex. But nested block comment might not be supported.

**Comment by bixuanzju** [comment]
@linusyang I think string interpolation can be delayed (not that important), having nested block comment is more desirable and easier.

**Comment by zonyitoo** [comment]
@linusyang It is not necessary to use `{` and `}` in block comment, just find another symbol. How about `(-` and `-)`?

**Comment by linusyang** [comment]
@zonyitoo All right. But I think they are equivalent in terms of implementation in the lexer.

**Comment by bixuanzju** [comment]
I'd prefer the Haskell way "{- ... -}" though.

**Comment by zonyitoo** [comment]
Me, too. String interpolation could use other symbols. Why string interpolation would conflict with nested comments?

**Comment by linusyang** [comment]
@zonyitoo I didn't say that. I mean _nested_ block comments might be a problem.
