### ISSUE TITLE
Improve `make test2`

### ISSUE THREAD

**Issue by bixuanzju** [hkuplg/fcore#135]
Since `make test` hasn't been finished yet, we rely on `make test2`. 
1. If some tests fail, should return 1
2. add summary of of successful and failed tests in the last.

Item 1 is more urgent in that travis then can kick in.

**Comment by bixuanzju** [comment]
@EmmaBYPeng Hi Emma, could you prioritise this task? Finish item 1 should be ok for now.

**Comment by EmmaBYPeng** [comment]
Sure! Working on it

**Comment by EmmaBYPeng** [comment]
Please the latest pull request. Item 1 finished.
