### ISSUE TITLE
Failed to clean *.class because of "argument list too long"

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#144]
There are too many `*.class` files was generated (over 2600 in my project), so the shell will complain about `argument list too long: rm`.

This should be fixed after module system was announced.

**Comment by zonyitoo** [comment]
One workaround is

``` bash
$ find . -type f -iname "*.class" -print0 | while IFS= read -r -d $'\0' line; do rm $line; done
```

**Comment by bixuanzju** [comment]
ref. #65
