### ISSUE TITLE
restore old style of type parameter

### ISSUE THREAD

**Issue by bixuanzju** [hkuplg/fcore#171]

**Comment by bixuanzju** [comment]
Because our type parameters are curried, it makes sense to have the following:

```
let fun A B (x: A) = x in
fun[Int][Bool] 3
```

**Comment by zonyitoo** [comment]
That looks odd....

**Comment by bixuanzju** [comment]
The point is, writing function like

```
let fun[A,B] (x: A) = x in
fun[Int][Bool] 3
```

would give the impression that `fun` cannot be curried on type parameters `A` and `B`, as in Scala. But `fun[Int]` is actually valid in our language.

Ideally we would not want to have brackets for type applications either, but that would cause problems for parsing.

**Comment by zhiyuanshi** [comment]
@bixuanzju Yep. I'm aware of this issue but would put it on low priority.

**Comment by bixuanzju** [comment]
@zhiyuanshi well, after the compiler meeting yesterday, we agreed to make that change ASAP. Would that involve lots work?

**Comment by zhiyuanshi** [comment]
@bixuanzju Not very complicated. I will raise priority as folks demand it.

**Comment by zhiyuanshi** [comment]
@bixuanzju @brunocdsoliveira Well, I noticed that the old style is still supported according to [the production](https://github.com/hkuplg/fcore/blob/develop/lib/Parser.y#L297) in parser.
