### ISSUE TITLE
Wiki is messy and contains semi-relevant stuff

### ISSUE THREAD

**Issue by tomtau** [hkuplg/fcore#175]
What's the purpose of keeping it when most important information is in https://github.com/hkuplg/fcore/tree/develop/doc or readme?

Current Wiki content is a bit random and not relevant to this particular repository -- maybe we should move it to this one: https://github.com/hkuplg/hkuplg.github.io ?

**Comment by bixuanzju** [comment]
I closed Wiki. Information of our group goes into our offiical group page
