### ISSUE TITLE
Merge the 'develop' branch into 'ghc-7.10'

### ISSUE THREAD

**Issue by zhiyuanshi** [hkuplg/fcore#209]

**Comment by bixuanzju** [comment]
#210

**Comment by zhiyuanshi** [comment]
Thanks. But I'm afraid that you misunderstood the direction of the merge...

**Comment by bixuanzju** [comment]
@zhiyuanshi What's the matter? I first merged develop into ghc-7.10, resolved the conflicts, then merged it back to develop in order that you can see clearly what have been changed based on your refactoring.

**Comment by bixuanzju** [comment]
Ref #212

**Comment by zhiyuanshi** [comment]
Ok, maybe using stack on develop is too early? I planned to work on ghc-7.10 with you.
