### ISSUE TITLE
Weird substitution problem v2

### ISSUE THREAD

**Issue by tomtau** [hkuplg/fcore#27]
There is an example that should typecheck. See the code below:

``` haskell
let getTwo [A,B] (x: A): A = x;
let getThree [A,B,C] (y: B): B = getTwo [B,C] y;
getThree [Int,String,Int] "abc"
```

Whereas f2j gives the "type mismatch" message:

```
expected: A
  actual: B
```

Everything is OK if the user tries to avoid such overlapping in source file. But that should be a bug in TypeCheck, and probably similar to the previous substitution problem.

**Comment by zhiyuanshi** [comment]
Related to [Capture-avoiding substitutions](http://en.wikipedia.org/wiki/Lambda_calculus#Capture-avoiding_substitutions).

Line 1: `getTwo : forall A B. A -> A`

Line 2 (expected): `getTwo [B, C] : forall B C. B -> B`

**Comment by wxzh** [comment]
This patch fixes the known bug in `fsubstTT`:

```
fsubstTT ("A", TVar "B") (Fun (TVar "A") (Forall "B" (Fun (TVar "A") (TVar "B"))))
Before: Fun (TVar "B") (Forall "B" (Fun (TVar "A") (TVar "B")))
After: Fun (TVar "B") (Forall "B1" (Fun (TVar "B") (TVar "B1")))
```
