### ISSUE TITLE
Propagate frontend name to generated backend

### ISSUE THREAD

**Issue by tomtau** [hkuplg/fcore#34]

**Comment by zhiyuanshi** [comment]
@wxzh Can you look at this?

**Comment by zhiyuanshi** [comment]
Is this done?

**Comment by tomtau** [comment]
@zhiyuanshi names are propagated, but not generated, because it'd involve quite a bit of changes in the backend, since variables are not only generated from the Closure F vars: the type representing vars in the backend should changed (for instance, in a few places, it pulls integer from the state monad and generates a variable with default name -- nothing in that context stores the original name)

**Comment by bixuanzju** [comment]
@tomtau Are you working on it now or you don't think it will be done any time sooner.

**Comment by tomtau** [comment]
I thought I could do it together with unboxing, since that also involves changing the type and rewriting the backend

**Comment by tomtau** [comment]
done in new-unboxing branch

**Comment by tomtau** [comment]
done in the new-unboxing branch
