### ISSUE TITLE
Create a better way for returning expressions that are not results of function applications in Stack Translation

### ISSUE THREAD

**Issue by tomtau** [hkuplg/fcore#36]
Currently, "createWrap" check whether the previous statements contain any "Next.next" assignments (which in this translation correspond to .apply() calls); if not, it creates an empyClosure to wrap the resulting expression, and assigns it to Next.next for the main body loop to be able to process it.

https://bitbucket.org/brunosoliveira/systemfcompiler/src/9b8f3a85d45e19208c9ef46ec62aceb77148961f/compiler/StackTransCFJava.hs?at=default#cl-103

**Comment by bixuanzju** [comment]
I think it has been properly done long ago.
