### ISSUE TITLE
Add infix operators

### ISSUE THREAD

**Issue by tomtau** [hkuplg/fcore#40]

**Comment by zonyitoo** [comment]
How about status of this issue?

**Comment by bixuanzju** [comment]
@zonyitoo Won't be implemented any time sooner.

**Comment by bixuanzju** [comment]
@lihuanglx So this is done?

**Comment by brunocdsoliveira** [comment]
There is a difference between infix operators and been anle to use prefix functions as infix functions. I believe Huang implemented the later, bit not the former.

**Comment by bixuanzju** [comment]
Alright, so
- [x] Using prefix functions with infix notation, e.g.,
  
  ``` haskell
  1 `add` 2
  ```
- [ ] Using infix functions with prefix notation, e.g.,
  
  ``` haskell
  (+) 1 2
  ```

**Comment by brunocdsoliveira** [comment]
Well, what I meant was, being able to define infix operators, such as:

(+++) :: [a] -> [a] -> [a]

in Haskell. Which then you can use as:

[1,2] +++ [3,4]

I believe this is also what @zonyitoo meant.

**Comment by zonyitoo** [comment]
@brunocdsoliveira Yes, exactly.

**Comment by zonyitoo** [comment]
@lihuanglx Seems it does not work with type parameters

```
-- ADT List
data PList[A] = Nil
              | Cons A (PList[A])
              ;

let cons[A] (v : A) (l : PList[A]) : PList[A] =
    Cons[A] v l;

1 `cons[Int]` (Nil[Int])
```

And it also failed to handle this case

```
let add (v : Int) (a : Int) (b : Int) : Int =
    v + a + b;

1 `add 2` 3
      ^~~~ Lexical Error
```

**Comment by wxzh** [comment]
1. Define something like `let conInt = cons[Int]` will avoid the problem
2. Application inside backquote is not allowed, even in Haskell

BTW, `cons` (and `length`, `nil` ...) has been occupied as a keyword. @zonyitoo

**Comment by zonyitoo** [comment]
@wxzh Alright. Then the second one should not be allowed.

The first case should be supported.

**Comment by lihuanglx** [comment]
@zonyitoo Type parameters supported.

```
let theSecond[A,B] (a:A) (b:B) = b;

1 `theSecond[Int,String]` "abc"                             ===> "abc"

1 `theSecond[Int,String]` "abc" `theSecond[String,Int]` 6   ===> "6"
```

**Comment by lihuanglx** [comment]
Sorry.. misclicked

**Comment by zonyitoo** [comment]
@lihuanglx excellent

**Comment by lihuanglx** [comment]
```
let (++) (x:String) (y:String) : String = x.concat(y);

"ab" ++ "cd" 
```

Or regard `(++)` as a normal function as below.

```
let (++) (x:String) (y:String) : String = x.concat(y)
and gao (f:String->String->String) (a:String) (b:String) : String = f a b;

gao (++) "ab" "cd"

(++) "ab" "cd"
```

**Comment by zonyitoo** [comment]
@lihuanglx  Is that work now? Here is a parse error

```
let (:)[A] (a : A) (l : PolyList[A]) = Cons[A] a l;
```

**Comment by zonyitoo** [comment]
@lihuanglx how to call this function

```
let (++)[A] (a : PolyList[A]) (b : PolyList[A]) : PolyList[A] = ...
```

how to apply the type parameter??

**Comment by lihuanglx** [comment]
@zonyitoo 
1. Only `!#$%&*+./<=>?@\^|-~` supported, please try another symbol instead `:`.
2. Just like a normal function, `list1 ++[Int] list2`.The type inference is not strong enough now, so it needs explicit type notation -_-||.

**Comment by zonyitoo** [comment]
@lihuanglx alright, sounds reasonable. ;)

**Comment by zonyitoo** [comment]
@lihuanglx i can't define an operator named `<+>` or `<|>`? They are in your supported list.

**Comment by lihuanglx** [comment]
```
let (<+>) [A] (a : A) (b: A) = a;
1 <+> 2
```

Maybe you forgot the parentheses?

Like Haskell, it requires parentheses in the definition.

**Comment by zonyitoo** [comment]
@lihuanglx Ah!!! Stupid mistake! Thanks!!!

**Comment by bixuanzju** [comment]
@lihuanglx Do you consider this feature fully implemented?

**Comment by lihuanglx** [comment]
@bixuanzju Yes, it should be closed now.

**Comment by brunocdsoliveira** [comment]
@lihuanglx Do you allow infixity declarations for the operators, as in Haskell?

**Comment by lihuanglx** [comment]
@brunocdsoliveira 

Sorry, I didn't take that into consideration. I'll improve it.

The new goal is to allow:

```
let a <+> b = a + b
let a `add` b = a + b
```

**Comment by zonyitoo** [comment]
@lihuanglx How about associativity?

**Comment by lihuanglx** [comment]
@zonyitoo All user defined operators have left associativity and the highest precedence.

**Comment by zonyitoo** [comment]
@lihuanglx it would be better if operators could supports right associativity, or you will have to add brackets around them.

**Comment by lihuanglx** [comment]
@zonyitoo Thanks, I'll consider that.

**Comment by bixuanzju** [comment]
@zonyitoo @lihuanglx In Haskell, you can define the associativity, say

``` haskell
infixr 9 <+>
```

I don't know if it's easy to implement in our language. Since most operators are left associative, it's reasonable to use it as default.

**Comment by zonyitoo** [comment]
@bixuanzju I agree with making left associativity as default, but some of the operators have to be right associative. Such as `:` in Haskell, or the magical `$` operator in Haskell.

**Comment by brunocdsoliveira** [comment]
@lihuanglx what I suggested above was to allow infixity declarations, such as the one Jeremy has shown:

```
infixr 9 <+>
```

so that the default settings can be overriden. This may require some more work. 

I didn't mean to allow this:

```
let a `add` b = a + b
```

This does not seem helpful to me.

**Comment by zonyitoo** [comment]
@lihuanglx Should this situation be allowed in F2J?

```
data Doc = Text String
         | Line Int
         | String `Text` Doc;
```

Also, I cannot use the constructor of data in infixop.

**Comment by zhiyuanshi** [comment]
@zonyitoo As to the first issue, I don't think so.

**Comment by zonyitoo** [comment]
@zhiyuanshi Why? Seems Haskell supports that.

**Comment by bixuanzju** [comment]
@zonyitoo You can't define a datatype like this, you have two constructors, both named `Text`

**Comment by zonyitoo** [comment]
@bixuanzju @zhiyuanshi Ahhhh, alright, that's a bad example...

**Comment by bixuanzju** [comment]
@zonyitoo Data constructors can't be used in infixop, that's true

**Comment by zonyitoo** [comment]
I think I should invite @Demonsu to demonstrate the problem. I don't know the detail of his problem.

**Comment by wxzh** [comment]
@zonyitoo  Do you mean that you want something like "1 `Cons` Nil "? It should be valid. I think there is a missing case in the parser for it. @lihuanglx

**Comment by zonyitoo** [comment]
@wxzh Humph.. yes, this case should be valid. But should this case be valid?

```
data Doc = Text String
         | Line Int
         | String `Union` Doc;
```

**Comment by wxzh** [comment]
@zonyitoo Yes, you can do this in Haskell. But why do you want to define it in this way? I don't see any   benefits it brings.

**Comment by zonyitoo** [comment]
@wxzh I don't know, is not me... I didn't use that in F2J, but I just curious about whether it should be included in F2J.

**Comment by xiafan-su** [comment]
Sorry guys. Yesterday, I was not sure that my pretty printer lib can be implemented without infix constructors. Then I mentioned it with Elton. It seems can be replaced by prefix. And I just finish it in f2j.

**Comment by wxzh** [comment]
@Demonsu It does not matter. You help us to find a bug in the Parser :). For now, you should always define functions and constructors in prefix annotation, but you can use them in infix annotation (after @lihuanglx fixes it).
