### ISSUE TITLE
Replace unsafeCoerce by undebruijn

### ISSUE THREAD

**Issue by tomtau** [hkuplg/fcore#49]
brunosoliveira created an issue 2014-10-14
Currently we are using unsafeCoerce to get cheap&quick coercions between PHOAS expressions. However I think this is a mistake. We should be using an undebruijn function. The benefit would be better debugging/error-messages and potentially a solution to the weird substitution issue (by enforcing a dedebruijn after every traversal).

**Comment by bixuanzju** [comment]
@hy-zhang confirmed no use of `unsafeCoerce`
