### ISSUE TITLE
Reduce I/O with typeserver during typechecking

### ISSUE THREAD

**Issue by tomtau** [hkuplg/fcore#52]
The idea would be to memoize valid Java constructs (class names, method call / field access signatures).
Before the improvement:
./run-tests-pipeline.sh  76.30s user 4.38s system 138% cpu 58.223 total
./run-tests-pipeline.sh  70.91s user 4.28s system 139% cpu 53.828 total
./run-tests-pipeline.sh  69.60s user 4.19s system 140% cpu 52.365 total
After memoizing valid Java class names:
./run-tests-pipeline.sh  70.92s user 4.39s system 140% cpu 53.694 total
./run-tests-pipeline.sh  68.37s user 4.26s system 140% cpu 51.601 total
./run-tests-pipeline.sh  68.51s user 4.31s system 140% cpu 51.781 total

**Comment by zhiyuanshi** [comment]
Done.
