### ISSUE TITLE
Require supporting of module and namespace

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#65]
Currently, F2J has already had module grammar as describe in `examples/module.sf`, but does not have support for writing modules in separated files. So I suggests that we could support it by simply copy and paste module files' content into one file, just like `#include` command in C.
## Simple Example

Here is the example in `examples/module.sf`

```
module M
  add (a:Int) (b:Int) : Int = a + b;
  sub (a:Int) (b:Int) : Int = a - b
end

M.add 1 2
```

And lets assume we have the following dir structure:

```
- example
    - main.sf
    - M.sf
```

```
-- main.sf

module M;

M.add 1 2
```

```
-- M.sf
add (a:Int) (b:Int) : Int = a + b;
sub (a:Int) (b:Int) : Int = a - b
```

When compile the `main.sf`, compiler could copy all the content in `M.sf` to the location of `module M` and make it look just like `examples/module.sf`.
## Submodule

Assume we have the following dir structure:

```
- example
    - main.sf
    - M
        - mod.sf
        - add.sf
        - sub.sf
```

```
-- main.sf
module M;

M.add.add 1 2
```

```
-- mod.sf

module add;
module sub;
```

```
-- add.sf
add (a:Int) (b:Int) : Int = a + b
```

```
-- sub.sf
sub (a: Int) (b: Int) : Int = a - b
```

When compiling, compiler will try to find where the module M is in the current directory. If module "M" is a directory, it the main file of the module will be the `mod.sf`. So compiler will first need to "preprocess" the `mod.sf` and then paste it into the `main.sf`.
## Recursively Include

This case should be considered as compile error.

For example, we have the following directory structure:

```
- example
    - main.sf
    - mod1.sf
    - mod2.sf
```

```
-- main.sf

module mod1
```

```
-- mod1.sf

module mod2
```

```
-- mod2.sf

module mod1
```

This should not happen in the real world. If you want to call some function defined in `mod1` in `mod2`, just call it directly. And define the two modules in the _root_ of this module (example is a module), which is `main.sf` in this case.
## Namespace

For example, we have the following dir structure:

```
- example
    - main.sf
    - mod1
        - mod.sf
        - mod2
            - mod.sf
            - mod3
                - mod.sf
```

If you want to call a function `func` that is defined in `mod3`, you will have to call it with `mod1.mod2.mod3.func`. It may be too long for typing.

So if possible, we could have a new keyword like `use` just like Rust and C++.
## Limitation
- This method will not provide any supports for importing external compiled libraries.

**Comment by EmmaBYPeng** [comment]
Actually a simple non-recursive module system is already supported in the module branch (for both f2j and f2ji). I haven't merged it into develop yet.

**Comment by zonyitoo** [comment]
@EmmaBYPeng Excellent. Could you write some examples here?

**Comment by EmmaBYPeng** [comment]
1. Link modules with source file:
   - f2j: `-l --module=MODULE`
   - f2ji: `:link <sourceFile> -m <module1> <module2> ...` 
2. f2ji:
   - `:load M` Load module M into REPL environment, allow user to use functions defined in M, say M.add
   - `:import M` Allow user to directly use add instead of M.add

**Comment by EmmaBYPeng** [comment]
There are some more examples of module (module1.sf, module2.sf, etc) in fcore/compiler.

**Comment by zonyitoo** [comment]
@EmmaBYPeng Seems that I cannot define `data` or `type` in module currently.

Because I got parse error on this

```
module Def {

    data PolyList [A] = Nil
                  | Cons A (PolyList[A]);

    type PolyString = PolyList[Char];

    type Parser [A] = PolyString -> PolyList[(A, PolyString)]

}
```

This won't be so useful in practice if module just supports function definitions.

**Comment by EmmaBYPeng** [comment]
A modules will be desugared to a record. Please refer to its implementation here https://github.com/hkuplg/fcore/wiki/Module%20System. Also, I think @zhiyuanshi understands better about the implementation of modules.

**Comment by brunocdsoliveira** [comment]
@EmmaBYPeng We should probably discuss some feature enhancements for modules. I agree with @zonyitoo that there are important features missing at the moment.

**Comment by EmmaBYPeng** [comment]
@brunocdsoliveira Agree.

**Comment by bixuanzju** [comment]
@EmmaBYPeng Hi Emma, are you working on that now?

**Comment by EmmaBYPeng** [comment]
Yep!

**Comment by EmmaBYPeng** [comment]
@zonyitoo Do you expect to mix data, type and function declarations together in a single module or is it ok if they are in separate files?

**Comment by zonyitoo** [comment]
@EmmaBYPeng It would be better if I can define data, type and function together, in one file. Just like what Haskell did.

**Comment by zonyitoo** [comment]
@EmmaBYPeng BTW, I think you should also consider about the unified entrance of the program when modules are supported. Such as the `main` function in most of existing languages.

**Comment by EmmaBYPeng** [comment]
@zonyitoo Hi, since we decided that our current aim is not to have a complex module system but one with basic functionality, C-like include is implemented for including files, also namespace is supported. Examples:
DataM.sf:

```
include M5
include M4

let null [A] (xs: M5.PolyList[A]): Bool =
    case xs of
       Nil -> True
     | Cons y ys -> False;

let headIs0 (xs : M5.IntList) : Bool =
   case xs of
       Nil -> if null [Int] xs
              then False
              else True -- unreachable
     | Cons y ys -> if null [Int] xs
                    then True -- unreachable
                    else y == 0;

headIs0 (Cons [Int] 0 (Nil [Int]))
--headIs0
```

M5.sf:

```
data M5.PolyList [A] = Nil
                | Cons A (M5.PolyList[A]);

type M5.IntList = M5.PolyList[Int];
```

M4.sf

```
module M4 {
  id[A] (x: A): A = x
}
```

Use `f2j -r DataM.sf` to directly run the file.

**Comment by bixuanzju** [comment]
@EmmaBYPeng That's cool, well done!

BTW, when defining functions in a module, we need to wrap them in `module name { ... }`, right? But writing datatype definitions requires writing namespace for each one (like in `M5.sf`). This is kinda inconsistent. Can it be improved?

**Comment by EmmaBYPeng** [comment]
@bixuanzju, that's right. It's because `module name {...}` will be desugared to a record so that we can access its field by M.f, while datatype definitions are just copied and pasted into the source file (actually in DataMc.sf), and M.T will become M_T. But that's indeed a problem, I'll see what I can do!

**Comment by zonyitoo** [comment]
@EmmaBYPeng Awesome, I will try it later!!

**Comment by xnning** [comment]
@brunocdsoliveira  About the List support, how about having some *.sf file inner our system, then things like inner List support can be removed and replaced by a List.sf file where List datatype is defined with some utilities. User can `include` the file if they want to use List. (works like a library or package such as Data.List in Haskell)

**Comment by zonyitoo** [comment]
@xnning I strongly agree!!! If that is allowed, then I could contribute those built-in libraries!

**Comment by zonyitoo** [comment]
@EmmaBYPeng Also, if you use the mechanism that what C actually did, the compiler have to be able to solve recursive including.

Also, is it possible to provide a `use` keyword as the one in C++/Rust.

And

```
include b;
         ^~~~~ I think this semicolon should not be omited for consistency
```

How about the search path? Compiler should know where could it looking for *.sf files. And will you support importing a module in folders?

**Comment by bixuanzju** [comment]
@zonyitoo I am going to create another issue for writing libraries. Would you be interested? Then I can assign to you.

**Comment by EmmaBYPeng** [comment]
@zonyitoo I'll look more into the recursive include thing. For modules in a folder, you can write `include lib/M5` if M5.sf is in folder lib (i.e. just use the path that leads to the file).

**Comment by zonyitoo** [comment]
@EmmaBYPeng How about including standard library? User will not want to specify the absolute path to the standard library. How about this
1. Compiler have a search path. It will try to find the one by iterating every folder in the search path.
2. Support absolute include, such as `include .List`, which will find the `List.sf` that located in the current directory.
3. Support import module as a folder, just like what I mention on the top post of this issue. Every folder as a module, it will have a central file with unified name, such as `mod.sf`. Compiler will try to include `mod.sf` instead of including one specified file inside that folder.
4. Those files in the same folder of one module, you have to `include` them inside the central file, so that other one can use it by `include M.somefile.somefunc`.

The idea is borrowed from Rust.

**Comment by EmmaBYPeng** [comment]
That's a fair request. I'll look into it as well.

**Comment by zonyitoo** [comment]
@EmmaBYPeng If you support this, I will suggest to use `module` as keyword instead of `include`.

**Comment by bixuanzju** [comment]
Implement a simple module system (allowing declarations in the language)

**Comment by bixuanzju** [comment]
Most done, in favour of #201
