### ISSUE TITLE
Syntax changes?

### ISSUE THREAD

**Issue by bixuanzju** [hkuplg/fcore#66]
Latest work on branch `feature/syntax-improvements` seems to change syntax again?
- Do we need to put brackets around type params both in definitions and type applications?

```
let id [A] (x : A) = x; id [Int] 3
```

will work, while the following won't

```
let id A (x : A) = x; id [Int] 3
```
- No `let <exp> in <exp>` syntax?

```
let id [A] (x : A) = x
in id [Int] 3
```

has parse error.

**Comment by zhiyuanshi** [comment]
Yes, as in Scala. `in` has been replaced by `;`.

For the latest syntax, please refer to:
https://github.com/hkuplg/fcore/blob/develop/doc/cheatsheet.md

**Comment by bixuanzju** [comment]
Could you also look at `example` directory, some of the previously fixed example are broken again.

**Comment by zhiyuanshi** [comment]
Fixed. The examples for modules don't compile as they won't without linking.

I'd like to ask Haoyuan to look at `examples/ObjectAlgebra_SybAlg_{runpass,runfail}.sf` (already assigned in another issue)
