### ISSUE TITLE
Unexpected compile error

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#70]
```
data PolyList A = Nil
                | Cons A (PolyList[A]);

type PolyString = PolyList[Char];

let rec fromString (str : String) : PolyString =
    if length(str) == 0 then
        (Nil[Char])
    else
        (Cons[Char] head(str) (fromString tail(str)));

fromString "abcdefg"
```

It seems that the compiler got into a infinity loop, because it replies

```
test using [Naive]
Compiling to Java source code ( ./Test.java )
f2j: <<loop>>
```

**Comment by xnning** [comment]
String is a java class but length, head, tail are for List.

So you should use java method, write code like

str.isEmpty(),
str.substring()

Or you can change to use List<Char>, then you can use head tail and length

Unfortunately, here String is not a synonym of List<Char>

2015-03-03 17:51 GMT+08:00 Y. T. CHUNG notifications@github.com:

**Comment by zonyitoo** [comment]
@xnning Thank you for the solution, but this approach brings out a new question:

```
let func (a : Char) = a;
func "abc".charAt(0)
```

Compiler said expecting `Char` but found `char`.

But if I try to replace this piece of code to

```
let func (a : Char) = a;
func Char.valueOf("abc".charAt(0))
```

Compiler complains that 

```
test_str using [Naive]
Compiling to Java source code ( ./Test_str.java )
./Test_str.java:17: 错误: 意外的类型
    final java.lang.Character x6 = java.lang.Character.<char>valueOf(x5);
                                                        ^
  需要: 引用
  找到:    char
1 个错误
错误: 找不到或无法加载主类 Test_str
rm: *.class: No such file or directory
```

Those Chinese means that `<char>` is an unexpected type.

**Comment by zonyitoo** [comment]
cc: @zhiyuanshi

**Comment by bixuanzju** [comment]
> ```
> let func (a : Char) = a;
> func "abc".charAt(0)
> ```
> 
> Compiler said expecting Char but found char.

This is a bug. Maybe related to `TypeServer`. Long time ago, I added a kludge to `TypeServer`: if the Java method returns primitives types, `TypeServer` won't box them, e.g. `int` won't become `Integer`. 

Apparently `charAt` returns primitive type `char`, so when type-checking, the type checker will see `JType (JPrim "char")` .

I am not sure how the type `Char` in our language is represented, need to ask @zhiyuanshi

**Comment by zonyitoo** [comment]
@bixuanzju I remember that @zhiyuanshi have told me `Char` is actually represented as `java.lang.Character`.

**Comment by bixuanzju** [comment]
Then `JType (JPrim "char")` should be equivalent to `JType (JClass "java.lang.Character")` when type-checking

**Comment by zhiyuanshi** [comment]
@zonyitoo: You're right. As a user of the compiler, he should be able to regard all primitive types in F2J as boxed types in Java and not worrying about boxing and unboxing. But from an implementation point of view in Java there are primitive types.

@bixuanzju: I think another approach is that let type server return boxed types only (for example, return `String` if it finds a `string`). In this way, the distinction between unboxed and boxed types won't propagate to our type checker, which I find to be a cleaner solution. I am sure the frontend will be happy. But is this loss of precise information a problem for the backend during code generation?

**Comment by bixuanzju** [comment]
@zhiyuanshi This is exactly what `TypeServer` did before I toke over until we had a bug that made me change a bit some time ago. I need to dig a bit to see if I can still find that example

**Comment by bixuanzju** [comment]
cc @zonyitoo Only `char` and `Character` are affected. Other primitive types will be returned as boxed types.

**Comment by bixuanzju** [comment]
Please refer to this [page](https://github.com/hkuplg/fcore/wiki/Quick_and_Dirty#jvm-type) on the Wiki. I documented some temporary hacks we had.

**Comment by bixuanzju** [comment]
I found the old issue, see below:

> I see the following code snippet in `TypeServer.java`:
> 
> ``` java
> static {
>         map.put(boolean.class, Boolean.class);
>         map.put(byte.class, Byte.class);
>         map.put(short.class, Short.class);
>         map.put(char.class, Character.class);
>         map.put(int.class, Integer.class);
>         map.put(long.class, Long.class);
>         map.put(float.class, Float.class);
>         map.put(double.class, Double.class);
>         map.put(void.class, Void.class);
>     }
> ```
> 
> Which basically wraps each primitive type into its corresponding class type. Are there some rationals behind? I ask this because in our benchmark program rundfa, I have a Java method call like `str.current()`, which, according to Java doc, should return `char`. However in our compiler, it returns `Character`. That's why our version of `rundfa` runs slower than that of Java 8 and Scala.

So the change is mainly for performance. Since now the new `unboxing` is under development, maybe this change should be reverted.

**Comment by bixuanzju** [comment]
@zonyitoo Does 9ced02f fix for you?

**Comment by zonyitoo** [comment]
@bixuanzju Cool, it fixed.
