### ISSUE TITLE
Need support of escaping characters in String and Char constant

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#72]
```
"\""
```

and

```
'\''
```

Should be compiled successfully

**Comment by brunocdsoliveira** [comment]
This should be addressed soon. It should be an easy thing todo. Please increase the severity.

**Comment by zhiyuanshi** [comment]
@linusyang Are you interested in doing this to get started with the hacking?

**Comment by linusyang** [comment]
@zhiyuanshi This is related to the lexer part (`compiler/Lexer.x`), right?

**Comment by zhiyuanshi** [comment]
@linusyang Yes. We use [Alex](https://www.haskell.org/alex/) to generate the lexer.

**Comment by linusyang** [comment]
@zhiyuanshi Thanks! Let me write a quick fix for this.

**Comment by zhiyuanshi** [comment]
@linusyang Thanks!

**Comment by linusyang** [comment]
@zhiyuanshi Check if #80 works, which follows the Java standard (`\uDDDD`) but not C style standard (`\xDD`) for better interoperability and Unicode support. BTW, the unescape funtion is taken directly from Language.Java. :)

**Comment by zhiyuanshi** [comment]
@linusyang I had a brief look and the code you committed looks like a pro :+1:. I'm in a work groove and will check it out more carefully later.

**Comment by linusyang** [comment]
@zhiyuanshi Because the code with comments is taken from Language.Java. :P Anyway, thanks a lot!

**Comment by zonyitoo** [comment]
Cool
