### ISSUE TITLE
Asking feature supports of builtin collection types and tuple

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#74]
I think built in types, like `List` and `String` should be a `PolyList[T]` and `PolyList[Char]`. So we can use pattern match to operate every elements of the `List` and `String`.

And we may need a syntax sugar of creating a `List`, such as `[]`, `[1]`, `[1, 2, 3]`.

If the infix operator is ready, we could also have `:` operator.

For tuples, it should be possible to extract contents in the tuple by pattern matching. Such as

```
let function ( (a, b) : (Int, Int) ) : (Int, Int) = (a, b);
```

**Comment by zonyitoo** [comment]
If we wants to call Java methods with `List` and `String` as arguments or return values, there have to be some approaches to convert `List` from/to `java.util.List` and `String` from/to `java.lang.String`. This could be built in the compiler.

**Comment by zhiyuanshi** [comment]
As to your last point, actually there is no need for conversion at least for `String`, as type constants are all Java types. Documented here: https://github.com/hkuplg/fcore/blob/develop/doc/cheatsheet.md

**Comment by zonyitoo** [comment]
@zhiyuanshi In Java, `String` and `List` is not the same thing. It will be much more convenient to use `String` as a `List[Char]`.

**Comment by zonyitoo** [comment]
I had some thoughts about how to implement the `List[T]`. A _List_ in functional programming language is actually a immutable data structure. So there are some possible references about immutable collections on Java, such as http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableList.html.

If we use a `java.lang.String` directly in functional programming language, it may not possible to have lazy evaluation on the String type because the `java.lang.String` is an immutable data structure and it uses an array as an underlining data structure to store `char`s data. Every modification operation on the `java.lang.String` will cause reallocation and data copy.

If we could write most of our code in a "F2J" ways, we could do some hacks when we need to call a Java method. Such as write some COW data structures in runtime or else.

**Comment by brunocdsoliveira** [comment]
@xnning Perhaps you can look into this? I think the first step would be to study support for pattern matching of strings in Scala. Then we could discuss possible implementation options.

**Comment by xnning** [comment]
ok, it's mine!

**Comment by xnning** [comment]
the prevalent way to support pattern matching of string in scala is using Regex. [API of Regex](http://www.scala-lang.org/api/current/index.html#scala.util.matching.Regex)

It uses regular expression to match string, and extracts groups from strings. 
example code modified from the api link. Here  date is a Regex. Here are three groups each wraps in brackets in date.

```
val date = """(\d\d\d\d)-(\d\d)-(\d\d)""".r
"2004-01-20" match {
  case date("2004",month, day) => "1"
  case date(year, month, day) =>  "2"
}
```

The case expression here is the Extractor Pattern, which will call the unapplySeq(...) of the Regex.
[Extractor Pattern](http://www.scala-lang.org/files/archive/spec/2.11/08-pattern-matching.html#extractor-patterns)

The Regex uses Java library java.util.regex.{Pattern, Matcher}  to do the match.
[Regex source code of scala](https://github.com/scala/scala/blob/v2.11.6/src/library/scala/util/matching/Regex.scala#L1)

To implement this in f2j, we can also use java.util.regex.{Pattern, Matcher} to create our Regex class, and do some modifications in current case expression. Specific implementation can be discussed further.

**Comment by xnning** [comment]
A simple syntax sugar for pattern matching on string is available.

```
case s of
    []   -> e1
  | c:cs -> e2

```

it will be desugared to

```
if (s.isEmpty())
then e1
else
  let c = s.charAt(0);
  let cs = s.substring(1);
  e2
```

Hope it will make coding a little bit easier..

**Comment by brunocdsoliveira** [comment]
Thanks Ningning!

**Comment by bixuanzju** [comment]
see #131
