### ISSUE TITLE
The name of type constructor and data constructor can be the same

### ISSUE THREAD

**Issue by wxzh** [hkuplg/fcore#76]
```
data T = T Int;
T 5
```

Issue using [Naive]
Compiling to Java source code ( ./Issue.java )
./Issue.java:12: error: class T is already defined in method apply()
      class T extends T
      ^
1 error

**Comment by xnning** [comment]
It is fixed now. it will rename the constructor name to be T1 when generating code in the back end.

**Comment by zhiyuanshi** [comment]
What will happen if `T1` is already bound?

**Comment by zhiyuanshi** [comment]
``` haskell
data T  = T | T1;
T
```

gives

```
should_run[develop*] % f2j EponymousDataCon.sf -r
EponymousDataCon using [Naive]
Compiling to Java source code ( ./EponymousDataCon.java )
./EponymousDataCon.java:19: error: variable T1 is already defined in class T
      T T1;
        ^
./EponymousDataCon.java:20: error: method T1() is already defined in class T
      T T1 ()
        ^
2 errors
```

**Comment by xnning** [comment]
sorry forgot number is allowed. 

Change the solution to make all name a concatenation of datatype name and constructor name will fix it then.
