### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by zhiyuanshi** [hkuplg/fcore#78]
## Motivation

String concatenation is prevalent in a pretty printer. As the size of program grows, calling the Java `concat` method on Strings soon becomes tedious and the code is hard to read. For example,

```
"before = ".concat(before.toString()).concat(", after = ").concat(after.toString())
```

Therefore, I propose the support of [string interpolation](http://en.wikipedia.org/wiki/String_interpolation) in our compiler. This can be one scheduled feature. The priority will depend on the manpower we have.
## How it works

The same string can be written as:

```
"before = \{before}, after = \{after}"
```

An item inserted into the string literal is wrapped inside a pair of curly parentheses, prefixed by a backslash (we call this the **"pattern"**). The item can be any expression. Interpolated string is then desugared into the very first snippet. String interpolation should be **type-safe** for the run time of Java programs:
- if the type of the item is `String`, it stay as is;
- else if the type is some Java class, the `toString` method will be implicitly called on it;
- else: type error.

**Note:** Interpolation is only processed inside a whole string literal. For example, the following:

```
let s = "hello";
"\{".concat("hello").concat("}")
```

won't be regarded as interpolation even though `"\{".concat("hello").concat("}")` evaluates to `"\{hello}"`, since the pattern `"\{...}"` does not appear inside any whole string literals. The purpose of this restriction is to prevent the dynamic construction of _patterns_ which bypasses the type checker.

**Comment by zonyitoo** [comment]
I think `\{` should be considered as an error. The character follows `\` should be escapable. 

I know the parser can deal with this situation, but sometimes this should be a bug in a program.

**Comment by brunocdsoliveira** [comment]
Perhaps this can be assigned to ningning or linusyang if they feel like doing some implementation?

**Comment by linusyang** [comment]
@brunocdsoliveira Okay. Let me try it if @xnning is busy with other issues. Do we need to polish the current proposed syntax of interpolation, @zhiyuanshi ?

**Comment by zhiyuanshi** [comment]
@linusyang Not sure. Check this out: http://en.wikipedia.org/wiki/String_interpolation

**Comment by bixuanzju** [comment]
@linusyang Hi Linus, are you going to pick the task?

**Comment by linusyang** [comment]
@bixuanzju Sure. The current proposal for string interpolation is all right for me. I'll follow this syntax.

**Comment by bixuanzju** [comment]
@linusyang Nice! I will assign the task to you.
