### ISSUE TITLE
Nesting If and "Data" Question

### ISSUE THREAD

**Issue by dynastywind** [hkuplg/fcore#81]
I wrote a sample code trying to use nesting Ifs but failed. Is it impossible to write nesting if in F2J now?

Besides, I write 
data Option[T] = Some T | None in my code, but the compiler says that the place where "[" appears has error. Is there any who could help me to solve this problem? Thank you.

**Comment by brunocdsoliveira** [comment]
It will probably be useful to paste your code here so that we can try the code and send you a fix.

**Comment by xnning** [comment]
nested if works, like

```
let a = 1 and b = 1;
if a == 1
  then if b == 2
         then 1
         else 2
  else 3
```

Currently in data declare, [] is no need in left side,

```
data Option T  = Some T | None
```

Btw, is it better to have [] in left sides to consist with function declare?

**Comment by wxzh** [comment]
@xnning The syntax has been changed to be the same as type synonyms, so [] is needed on the LHS.
@dynastywind  You can refer to https://github.com/hkuplg/fcore/blob/develop/doc/cheatsheet.md#expressions
or examples under https://github.com/hkuplg/fcore/tree/develop/examples/datatype

**Comment by xnning** [comment]
i seen. Pull the latest version, then the original Option declare should work.

**Comment by dynastywind** [comment]
@wxzh 
What I want to do is to write a function that extract an element from a java List according to the index by firstly checking if it is out of the list's bound. Below is my code.

type MyList = java.util.ArrayList;
data Option T = Some T | None;
let addValue (list: MyList) (value: Char) = list.add(value);
let getValue (list: MyList) (index: Int) = 
    if list.size() > index then
        Some (list.get(index))
    else
        {list.get(0);None};
let l: MyList = new java.util.ArrayList( );
{addValue l 'a'; addValue l 'b'; getValue l 2}

It doesn't work and how to fix it? Thank you.

**Comment by xnning** [comment]
if you have the latest code, then 

```
data Option [T] = Some T | None;
```

is correct. Please do keep the [] in LHS.

Because Option has type parameter, Some and None both need to have type application.
Change the getValue function to be

```
let getValue (list: MyList) (index: Int) =
if list.size() > index then
Some [java.lang.Object] (list.get(index))
else
{list.get(0);None [java.lang.Object]};
```

**Comment by wxzh** [comment]
As Ningning suggested, you need to write the type **explicitly** every time you use a data constructor belonging to a parameterised datatype. 

BTW, there is also a support for generic list, see https://github.com/hkuplg/fcore/tree/develop/examples/list

**Comment by dynastywind** [comment]
@wxzh 
Is there any functions in hand that I can use to compare whether a string and a list of chars are correct or not? If not, how can I implement my own? Below is my code but runs into problems.

let rec equals (string: String) (chars: List<Char>) =
    if length(string) == length(chars) then
        if length(string) == 1 then
            if string.charAt(0) == head(chars) then
                True
            else
                False
        else
            string.charAt(0)==head(chars) && equals string.substring(0) tail(chars)
    else
        False;
equals "Hello" new List<Char>('H','e','l','l','l')
How to fix it? Thank you.

**Comment by wxzh** [comment]
When using `let rec` construct, you need to specify the return type explicitly

**Comment by brunocdsoliveira** [comment]
@dynastywind For questions please don't create issues. Issues are for bugs or feature requests. If you want to ask questions, please use either: 

1) The compiler mailing list;

2) The slack compiler channel.
