### ISSUE TITLE
CastException when running this example

### ISSUE THREAD

**Issue by bixuanzju** [hkuplg/fcore#83]
To reproduce, compile and run the following

```
let const [A, B] (x : A) (y : B) : A = x;
let const2 = const [Int];
const2 [Bool] 3 False
```

It type checks, but has cast exception

> Compiling to Java source code ( ./Main.java )
> Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
>     at Main.apply(Main.java:34)
>     at Main.main(Main.java:39)

**Comment by bixuanzju** [comment]
Strangely, the following can type check and run:

```
let const2 [B] (x : Int) (y : B) : Int = x;
const2 [Bool] 3 False
```

**Comment by bixuanzju** [comment]
With @hy-zhang we confirmed this is related to weird substitution issue (similar to simplifier)

**Comment by zhiyuanshi** [comment]
I'm still fixing #27. Hang tight.
