### ISSUE TITLE
A bug for currying

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#84]
I have encounter a weird bug (or a feature?) 

```
let function (str : String) = str;

let function2 (str : String) = str;

function function2 "abc"
```

One possible fix is to add brackets surrounding `function2 "abc"`. Our compiler will complain about type mismatch. Because `function` expects a `String` but `function2` is `String -> String`.

It seems that F2J does not supports currying, because the following piece of code does not work too.

```
(function function2) "abc"
```

That doesn't make sense.

**Comment by brunocdsoliveira** [comment]
I think there are 2 different issues here: currying and type-inference. For currying it seems like there is a buig in the compiler. For type-inference that's a feature enhancement. We should be able to fix the first issue quickly. The second issue is much more challenging (although we certainly agree that it is a very desirable feature). 

Can you split the issues into 2: a bug for currying; and a feature request?

**Comment by zhiyuanshi** [comment]
I think currying is a false issue. The problem with the first example (even after you added the parens) is that it doesn't type check. Function application associates to the **left**. To make it type check, add parens. This works:

``` ocaml
let function (str : String) = str;
let function2 (str : String) = str;
function (function2 "abc")
```

**Comment by brunocdsoliveira** [comment]
Ah, yes. George is right.

**Comment by zonyitoo** [comment]
@zhiyuanshi I agree with the association. But what I mean in the example is the currying bug. But I don't know whether it is a type check bug or currying bug, so I put them together.

**Comment by zonyitoo** [comment]
@zhiyuanshi I agree with the fix (which I have already mention). But I think the following code should work too

``` ocaml
let function (str : String) = str;
let function2 (str : String) = str;
(function function2) "abc"
```

According to **LEFT** association, `function function2 "abc"` is equivalent to `(function function2) "abc"`. That exactly what I mean.

**Comment by zonyitoo** [comment]
@brunocdsoliveira Ok, I will split it to another issue.

**Comment by zhiyuanshi** [comment]
@zonyitoo No I don't think so. `function` expects a `String` but `function2` has type `String -> String`.

**Comment by brunocdsoliveira** [comment]
function function2 "abc" 

is indeed equal to

(function function2) "abc" 

and both of these are not well-typed. Try your example in Haskell (for example) and you'll see that Haskell behaves in the same way. The only correct thing is:

function (function2 "abc")

**Comment by brunocdsoliveira** [comment]
Generally speaking, before reporting a bug, it is a good idea to try out the code in another functional language, to make sure it is indeed a bug (and not a misunderstanding).

**Comment by zonyitoo** [comment]
Ok. I see...
