### ISSUE TITLE
let ... in ... expression have been removed?

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#85]
```
let x = "xxx" in x
```

Compiler reports an parse error.

**Comment by zhiyuanshi** [comment]
Yes, for consistency with other declaration-like constructs (`type`, `data`). Use `let x = e; e` instead. In the future we'll make semicolons optional.

If you have doubts about the supported syntax on the head of the develop branch,

https://github.com/hkuplg/fcore/blob/develop/doc/cheatsheet.md

should give you a quick helping hand.

**Comment by bixuanzju** [comment]
@zhiyuanshi George, can we have both `let e in e` and `let e; e`, cause `let e in e` is very handy for writing local definitions, whereas using `let e; e` you have to add brackets.
