### ISSUE TITLE
No parse error detection?

### ISSUE THREAD

**Issue by bixuanzju** [hkuplg/fcore#88]
The latest commit silents all parse errors

```
let a = 1 in a
```

this shouldn't be parsed, but the compiler happily accepts, and doesn't produce anything

```
⇒  f2j -r test.sf
test using [Naive]
Compiling to Java source code ( ./Test.java )
```

**Comment by EmmaBYPeng** [comment]
Ah...noted! (it's working fine with f2ji though...)

**Comment by EmmaBYPeng** [comment]
It should give a parse error now.
