### ISSUE TITLE
Compare between tuples

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#95]
```
(1) == (1)
-- returns True
```

```
(1, 1) == (1, 1)
-- returns False
```

The compiler will see the first case as a special case, which means that it will be compiled into

``` java
final java.lang.Boolean x16 = 1 == 1;
return x16;
```

I think we will need **Type Class** to solve this problem.

**Comment by zhiyuanshi** [comment]
I don't think this will be implemented any time soon. Priority should be lower than type inference at least.

**Comment by brunocdsoliveira** [comment]
Our type-checker should reject (1,1) == (1,1). Equality for tuples should be defined manually, by creating a function.

**Comment by bixuanzju** [comment]
ref. #96
