### ISSUE TITLE
Supports empty expression

### ISSUE THREAD

**Issue by zonyitoo** [hkuplg/fcore#99]
```
let func = ;
```

Compiler will report parse error on the above piece of code. But we can define the value of an empty expression has a _void_ value. It will be useful in `if` statement

```
let func (x : Int) =
    if x == 1
        -- Do nothing
    else
        print x; ; -- the value of expression in else statement is *void*
```

And there will not be a strong requirement that all `*.sf` file must not ends with `;`.

I suggest the _void_ value could be `()`.

**Comment by bixuanzju** [comment]
This sounds like doing side effects, I wonder what's the type of the _void_ value (or `()` as you suggest). 

If I am not mistaken, currently we have the `()` value of type `Unit`, so I think evaluating two expressions in sequence `e1; e2` is just a syntax sugar of `(\(x : Unit) -> e2) e1`. Translating your example to a valid f2j program:

```
let func (x : Int) =
  if x == 1
  then ()  -- Do nothing
  else java.lang.System.out.print(x); -- Unit type
func 3
```

Ironically, the above program crashes, a bug found :(

**Comment by zhiyuanshi** [comment]
By the way, I'm not a big fan of empty things. `()` is just a value, like others, and whitespace is not its name. But you can always explicitly put a `()` in the `if` branch. But we might consider equate

``` haskell
if e1 then e2
```

to

``` haskell
if e1 then e2 else ()
```

to make code that works mainly by condition + side-effects look better.

**Comment by bixuanzju** [comment]
@zonyitoo Just to clarify, do you want to add feature like "sequencing notation" (e.g. `e1; e2`), or you think `Unit` type is what you want?

**Comment by brunocdsoliveira** [comment]
I don't think we should allow empty expressions. This does not make sense in functional programming. What we should have is a transparent mapping from Java void type to Unit. So, for example, if we have:

System.out.println("Hello")

the type of this should show up as 

Unit

in our language. That's exactly what Scala does, I think.

**Comment by bixuanzju** [comment]
@brunocdsoliveira This is exactly the case in `f2j` now.

**Comment by zonyitoo** [comment]
`java.lang.System.out.print(x)` returns a Unit?

**Comment by zhiyuanshi** [comment]
@zonyitoo Please refer to Issue #101.

**Comment by zonyitoo** [comment]
@bixuanzju Does `f2j` already has "sequencing notation"? Because `"abc"; "abc"` is also a parse error. (`{ "abc"; "abc" }` works).

What I want in here is just to clarify that whether "empty expression" should be supported in `f2j`.

@zhiyuanshi Thanks.

**Comment by zhiyuanshi** [comment]
@zonyitoo Yep and you'll need to the enclosing curly braces and at least one expression inside. See the [Cheatsheet](https://github.com/hkuplg/fcore/blob/develop/doc/cheatsheet.md) and search for "Expression sequences".

**Comment by bixuanzju** [comment]
@zonyitoo Apparently I didn't know that we already had "expression sequences". 

I think "empty expression" is effectively equivalent to `()`. So you might want to write `()` when you mean empty expression. BTW, should this issue be closed?
